# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arduino Nano 33 BLE Guide
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Writeups/Webpage for all things Arduino Nano 33 BLE (nRF52840) related to help you get up to speed and experiment.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Enable or disable the site search
search_enabled: true

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil


# Build settings
#theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

#markdown: kramdown
#theme: minima
plugins:
  - jekyll-seo-tag

ga_tracking: UA-132340763-2
# logo: "/assets/images/just-the-docs.png"

footer_content: "Copyright &copy; 2019 Shantam Raj"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
